### ISSUE TITLE
Error in an author's name

### ISSUE THREAD

**Issue by DomInvivo** [mlresearch/v139#16]
For the "Directional Graph Networks" paper with author _Dominique Beaini_, there is a typo in the name of the author, one of the `i` is missing. It should be **Beaini** NOT **Beani**.

https://github.com/mlresearch/v139/tree/gh-pages/beani21a

**Comment by lawrennd** [comment]
You can submit the correction as a pull request. Simply go to the relevant abstract (while logged in to GitHub) and click the edit button. You can then make the edits in the GitHub editor. You'll need to edit both he author and tex_author fields.
